# 1. Create service account
#.   * Service Account Token Creator
#.   * Artifact Registry Writer
# 2. Generate service account key
#.   * In GitHub project -> Settings -> Secrets -> Actions -> New Repository Secret
#.     Name: GCP_CREDENTIALS
#.     Value: key.json contents
# 3. Create repo in artifact repository
#.   * Name: $env.REPOSITORY below
#.   * Region: $env.GAR_LOCATION below

name: Docker build and push to Artifact Registry

on:
  workflow_dispatch:
  workflow_call:

env:
  PROJECT_ID: casfee-adv-mumble
  GAR_LOCATION: europe-west6
  REPOSITORY: mumble-thierry-simon
  IMAGE: mumble-image

jobs:
  build:
    name: Docker login and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Docker login'
        uses: 'docker/login-action@v2'
        with:
          registry: europe-west6-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: 'Docker build and push'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            europe-west6-docker.pkg.dev/casfee-adv-mumble/mumble-thierry-simon/mumble-image:latest
            europe-west6-docker.pkg.dev/casfee-adv-mumble/mumble-thierry-simon/mumble-image:${{ github.sha }}
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            --platform linux/amd64
