name: Docker-GCP
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: smartive-education/app-thierry-simon
          path: app-thierry-simon

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/europe-west6-docker.pkg.dev/casfee-adv-mumble/mumble-thierry-simon/mumble-image:latest .

      - name: Push to Google Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/europe-west6-docker.pkg.dev/casfee-adv-mumble/mumble-thierry-simon/mumble-image:latest
