name: Code Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    name: Run Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@smartive-education'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ESLint Check
        run: npm run lint
      - name: Prettier Check
        run: npm run prettier:check
